<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netframework4.7.2</TargetFramework>
        <AssemblyName>Cecil ANSI Utils</AssemblyName>
        <Description>A library of ANSI Utilities for the C# Console environment, mainly Color Modes [foreground and background], and Text Processing Modes, also includes RGB Conversions for ColorRGB</Description>
        <Version>1.1.0</Version>
        <Authors>Organization Cecil Libraries, Founder(s) Chaosyr</Authors>
        <Company>Organization Cecil Libraries, Founder(s) Chaosyr</Company>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>Latest</LangVersion>
        <RootNamespace>ANSI_Utils</RootNamespace>
        <ApplicationIcon>CecilLibsLogo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>
    
    <PropertyGroup>
        <PackageId>Cecil.ANSI_Utils</PackageId>
        <PackageTags>ansi console terminal color formatting colorrgb color255 color256 rgbconversion consoleoutput consolefont</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/Cecil-Libraries/Cecil-ANSI-Utils</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReleaseNotes>
            * Added GetTypeVariant(), docs will have a updated section for it, but what it does is when a Color Object is present you can cast `GetTypeVariant(string\int)` and get the Object set to that Mode with the same Color. 
            * Similarly we also added `GetColorVariant` which works similarly but with the color, we reccomend not using both systems with a singular object it will get messy quick.
            * Added `ToggleBackground()` and `ToggleHighIntensity()` these will toggle the state of the given boolean on the Object itself.
            * RGB Tupples in the RGB Object related RGB sections, this was done for ease of Use with the RGB Conversions.
        </PackageReleaseNotes>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE.md" Pack="true" PackagePath="/" />
        <None Include="README.md" Pack="true" PackagePath="/" />
        <None Include="icon.png" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>