<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;netframework4.7.2;netframework4.8;netframework4.8.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
        <RuntimeIdentifiers>win-x64;win-x86;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm64;osx-x64;osx-arm64;browser-wasm</RuntimeIdentifiers>
        <AssemblyName>Cecil ANSI Utils</AssemblyName>
        <Description>A library of ANSI Utilities for the C# Console environment, mainly Color Modes [foreground and background], and Text Processing Modes, also includes RGB Conversions for ColorRGB</Description>
        <Version>1.2.0</Version>
        <Authors>Organization Cecil Libraries, Founder(s) Chaosyr</Authors>
        <Company>Organization Cecil Libraries, Founder(s) Chaosyr</Company>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>Latest</LangVersion>
        <RootNamespace>ANSI_Utils</RootNamespace>
        <ApplicationIcon>CecilLibsLogo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>
    
    <PropertyGroup>
        <PackageId>Cecil.ANSI_Utils</PackageId>
        <PackageTags>ansi console terminal color formatting colorrgb color255 color256 rgbconversion consoleoutput consolefont</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/Cecil-Libraries/Cecil-ANSI-Utils</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReleaseNotes>
            * Fixed Reset for Color Objects set as Bold.
            * Added Modes to Color Objects called "Doubleline", "Overline", "Framed", "Encircled".
            * Fixed Resets fully.
            * Updated the displayers to include the 4 new modes.
            * Toggle on Package Support for NetStandard2.0, NetStandard2.1, Framework4.8, Framework4.8.1, Net5, Net6, Net7, Net8, Net9, Net10
            * Toggle on Support for the following Redistributables; win-x64;win-x86;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm64;osx-x64;osx-arm64;browser-wasm
            Next Update aim is to support Java!! [NativeAOT], in the mean time if theres anything you want to request for the library dm @thincreator3483 on discord!
            Oh yeah btw, some of the new modes may not display because consoles are silly and dont support them, if someone wants to help I think it could be really cool to build our own Cecil-Console or something.
        </PackageReleaseNotes>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE.md" Pack="true" PackagePath="/" />
        <None Include="README.md" Pack="true" PackagePath="/" />
        <None Include="icon.png" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>