<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;netframework4.7.2;netframework4.8;netframework4.8.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
        <RuntimeIdentifiers>win-x64;win-x86;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <AssemblyName>Cecil ANSI Utils</AssemblyName>
        <Description>A library of ANSI Utilities for the C# Console environment, mainly Color Modes [foreground and background], and Text Processing Modes, also includes RGB Conversions for ColorRGB</Description>
        <Version>2.0.0</Version>
        <Authors>Organization Cecil Libraries, Founder(s) Chaosyr</Authors>
        <Company>Organization Cecil Libraries, Founder(s) Chaosyr</Company>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>Latest</LangVersion>
        <RootNamespace>ANSI_Utils</RootNamespace>
        <ApplicationIcon>CecilLibsLogo.ico</ApplicationIcon>
        <NoWarn>$(NoWarn);CS0618</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>
    
    <PropertyGroup>
        <PackageId>Cecil.ANSI_Utils</PackageId>
        <PackageTags>ansi console terminal color formatting colorrgb color255 color256 rgbconversion consoleoutput consolefont</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/Cecil-Libraries/Cecil-ANSI-Utils</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReleaseNotes>
        * Added Defaults for the Color object, less object creation required.
        * Changed the ANSICodeLists from string[] to IReadOnlyList&#60;string&#62;
        * Base Library code is now stored in a `Lib Core` subfolder.
        * Added NativeAOT support for the Full Library. [Present in the .Native DLL]
        * Fixed a bug where some ANSICodeLists ended with Text instead of List.
        * Built a proper build tool
        * Put together a Github Action to Automate release builds [The Ominious 140+ zips]
        </PackageReleaseNotes>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE.md" Pack="true" PackagePath="/" />
        <None Include="README.md" Pack="true" PackagePath="/" />
        <None Include="icon.png" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Cecil ANSI Utils Native\NuGet.Config" />
        <None Remove="Cecil ANSI Utils Native\obj\**" />
        <None Remove="Cecil ANSI Utils Native\bin\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Cecil ANSI Utils Native\obj\**" />
        <Compile Remove="Cecil ANSI Utils Native\bin\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Cecil ANSI Utils Native\obj\**" />
        <EmbeddedResource Remove="Cecil ANSI Utils Native\bin\**" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Remove="Native Core\**\*.cs" />
        <None Remove="Native Core\**\*.h" />
        <None Remove="GITHUB RELEASE\**\*.zip" />
        <None Remove="GITHUB PRERELEASE\**\*.zip" />
        <None Remove="GITHUB RELEASE\**\*.nupkg" />
        <None Remove="GITHUB PRERELEASE\**\*.nupkg" />
    </ItemGroup>
</Project>