name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS }}
          fetch-depth: 0

      - name: Create profile dir
        run: mkdir -p profile

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=github-readme-stats&theme=shades-of-purple&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage
          path: profile/pin-readme-tools-github-readme-stats.svg
          token: ${{ secrets.STATS }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.STATS }}
          commit-message: "Update README cards"
          title: "🤖 Update stats cards"
          body: "Automated update of profile cards"
          branch: update-stats-cards
          delete-branch: true
          base: main

      - name: Wait for status checks
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.STATS }}
          delay: 5s
          interval: 5s
          timeout: 1800s

      - name: Auto-approve PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.STATS }}
          number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.STATS }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash
